site_name: {{cookiecutter.plugin_name}}
site_description: {{cookiecutter.short_description}}
site_author: {{cookiecutter.full_name}}

theme: readthedocs

{% if cookiecutter.github_repository_url != 'provide later' %}
repo_url: https://github.com/{{cookiecutter.github_username_or_organization}}/{{cookiecutter.plugin_name}}
{% endif %}
pages:
- Home: index.md
